server {
    listen 80 default_server;

    add_header Access-Control-Allow-Origin * always;

    # Proxy API requests to backend
    location ^~ /api/v1 {
        proxy_pass http://backend/; # 'backend' is the service name in docker-compose
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header Cookie $http_cookie;
        proxy_cache_bypass $http_upgrade;
    }

    # Proxy requests to admin panel
    location ^~ /admin {
        proxy_pass http://admin/; # 'admin' is the service name in docker-compose
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header Cookie $http_cookie;
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # This is the magic line for SvelteKit SPA routing
        try_files $uri $uri/ /index.html;
    }
}