services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - default
    volumes:
      - archived-cards:/usr/share/nginx/html/archived-cards/
      - avatars:/usr/share/nginx/html/avatars/
      - artworks:/usr/share/nginx/html/artworks/
    depends_on:
      - backend
      - admin # We depend on admin here because NGINX will throw a fit if it's not available
  admin:
    build: ./admin
    hostname: admin
    networks:
      - default
    depends_on:
      - backend
  backend:
    build: backend
    hostname: backend
    networks:
      - default
    environment:
      DB_USER: nwero
      DB_PASSWORD: nwero
      DB_NAME: bingo
      DB_HOST: db
      DB_PORT: 5432
      ERROR_STACK_ENCRYPTION_KEY:
      DISCORD_APPLICATION_ID:
      DISCORD_APPLICATION_SECRET:
      DISCORD_REDIRECT_URI: https://bingo.nwero.net/
    volumes:
      - ./backend/data/:/bin/backend/data/
    depends_on:
      - db
  db:
    image: ./postgres
    environment:
      POSTGRES_PASSWORD: nwero
      POSTGRES_USER: nwero
      POSTGRES_DB: bingo
    networks:
      - default
    volumes:
      - ./postgres/00000000.db-init.sql:/docker-entrypoint-initdb.d/00000000.db-init.sql
      - postgres:/var/lib/postgresql

networks:
  default:
    internal: true

volumes:
  postgres:
  archived-cards:
  artworks:
  avatars: